---
- name: Import ohmyzsh playbook
  import_playbook: playbooks/ohmyzsh.yml

- hosts: localhost
  tasks:
    - include_vars: vars.yml

    - name: Create directories
      include_tasks: tasks/create_directories.yml

    - name: Install configs
      include_tasks: tasks/config.yml

    - name: SSH key
      include_tasks: tasks/sshkey.yml

    - name: APT
      include_tasks: tasks/apt.yml

    - name: Web development
      include_tasks: tasks/webdev.yml

    - name: Install oh-my-zsh
      include_tasks: tasks/oh-my-zsh.yml

    - name: Install gitconfig
      include_tasks: tasks/gitconfig.yml

    - name: Setup terminal
      include_tasks: tasks/terminal.yml

- name: Import docker playbook
  import_playbook: playbooks/docker.yml
