---
- name: create programs directory
  file:
    path: "{{ folders.homedir }}/{{ username }}/{{ folders.programs }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: create projects directory
  file:
    path: "{{ folders.homedir }}/{{ username }}/{{ folders.projects }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: create data directory
  file:
    path: "/{{ folders.homedir }}/{{ username }}/{{ folders.data }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
