---
- name: core.excludesfile
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: ~/.gitignore_global

- name: user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"

- name: user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: push.default
  community.general.git_config:
    name: push.default
    scope: global
    value: simple

- name: pager.diff
  community.general.git_config:
    name: pager.diff
    scope: global
    value: diff-so-fancy | less --tabs=1,5 -RFX

- name: pager.show
  community.general.git_config:
    name: pager.show
    scope: global
    value: diff-so-fancy | less --tabs=1,5 -RFX

- name: color.ui
  community.general.git_config:
    name: color.ui
    scope: global
    value: "true"

- name: diff.tool
  community.general.git_config:
    name: diff.tool
    scope: global
    value: "{{ git.difftool }}"

- name: difftool.prompt
  community.general.git_config:
    name: difftool.prompt
    scope: global
    value: "false"

- name: Insert extra in gitconfig
  blockinfile:
    path: ~/.gitconfig
    insertafter: EOF
    block: |
      [filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
      [color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22
      [color "diff"]
        meta = yellow
        frag = magenta bold
        commit = yellow bold
        old = red bold
        new = green bold
        whitespace = red reverse
      [difftool "meld"]
        cmd = meld "$LOCAL" "$REMOTE"
