---
- name: Add things to zsh config
  blockinfile:
    backup: true
    path: "{{ folders.homedir }}/{{ username }}/.zshrc"
    insertafter: EOF
    block: |
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi

      export PATH="$PATH:$HOME/.npm-global/bin"
      export PATH="$PATH:$HOME/.config/composer/vendor/bin"

      setopt completealiases

      if [ -f ~/.zshaliases.sh ]; then
        source ~/.zshaliases.sh
      fi

      if [ -f ~/.zshfunctions.sh ]; then
        source ~/.zshfunctions.sh
      fi

      # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
      [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

- name: Add powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ folders.homedir }}/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ folders.homedir }}/{{ username }}/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: zsh syntax highlightning
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ folders.homedir }}/{{ username }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
