---
- name: Check ssh key is installed
  stat:
    path: /home/{{ username }}/.ssh/id_rsa.pub
  register: ssh_installed

- name: Copy ssh key
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.ssh/
    mode: 0600
  with_fileglob:
    - sshkey/*
  when:
    - not ssh_installed.stat.exists

- name: Delete ssh key
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - sshkey/*
