---
- name: Check ssh key is installed
  stat:
    path: "{{ homedir }}/{{ username }}/{{ folder.ssh }}/id_rsa.pub"
  register: ssh_installed

- name: SSH setup
  when: not ssh_installed.stat.exists
  block:
    - name: Copy ssh key
      copy:
        src: "{{ item }}"
        dest: "{{ home }}/{{ username }}/{{ folder.ssh }}/"
        mode: "0600"
      with_fileglob:
        - sshkey/*
