---
- name: Install php ppa
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: php74
  include_tasks: php/packages.yml
  vars:
    phpv: php7.4
  when: php.v74 == true

- name: php80
  include_tasks: php/packages.yml
  vars:
    phpv: php8.0
  when: php.v80 == true

- name: composer
  include_tasks: php/composer.yml

- name: symfony
  include_tasks: php/symfony.yml
