- name: stat composer
  stat: path=/home/{{ username }}/{{ folders.programs }}/composer.phar
  register: stat_composer

- name: Install composer
  when: not stat_composer.stat.exists
  block:
      - name: download composer
        shell: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"

      - name: move composer
        file:
          src: composer.phar
          dest: /home/{{ username }}/{{ folders.programs }}/composer.phar

      - name: stat downloaded composer.phar
        stat: path=composer.phar
        register: stat_downloadcomposer

      - name: delete downloaded composer.phar
        file:
          path: composer.phar
          state: absent
        when: stat_downloadcomposer.stat.exists

      - name: delete download composer
        file:
          path: /home/{{ username }}/composer.phar
          state: absent

      - name: symlink composer.phar
        become: yes
        file:
          src: /home/{{ username }}/{{ folders.programs }}/composer.phar
          dest: /usr/local/bin/composer.phar
          state: link

      - name: symlink composer
        become: yes
        file:
          src: /usr/local/bin/composer.phar
          dest: /usr/local/bin/composer
          state: link

      - name: symlink c
        become: yes
        file:
          src: /usr/local/bin/composer.phar
          dest: /usr/local/bin/c
          state: link
