- name: download symfony
  get_url:
    url: https://github.com/symfony/cli/releases/download/v4.21.3/symfony_linux_amd64.gz
    dest: /home/{{ username }}/Programs/symfony.gz
    force: true

- name: unzip symfony
  shell: gunzip /home/{{ username }}/Programs/symfony.gz

- name: executeable symfony
  shell: chmod +x /home/{{ username }}/Programs/symfony

- name: symlink symfony
  become: true
  file:
    src: /home/{{ username }}/Programs/symfony
    dest: /usr/local/bin/symfony
    state: link
