---
- name: Is symfony installed?
  stat:
    path: "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony"
  register: symfony_installed

- name: Install symfony
  when: not symfony_installed.stat.exists
  block:
    - name: Determine latest symfony version
      shell: |
        curl https://get.symfony.com/cli/LATEST
      register: symfony_version

    - name: Download symfony
      shell: |
        wget -O "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony.gz" https://github.com/symfony/cli/releases/download/v{{ symfony_version.stdout }}/symfony_linux_amd64.gz
      when: symfony_version.stdout is defined

    - name: Download symfony (undetermined version)
      shell: |
        wget -O "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony.gz" https://github.com/symfony/cli/releases/download/v4.26.9/symfony_linux_amd64.gz
      when: symfony_version.stdout is undefined

    - name: unzip symfony
      shell: gunzip "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony.gz"

    - name: executeable symfony
      shell: chmod +x "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony"

    - name: symlink symfony
      become: true
      file:
        src: "{{ homedir }}/{{ username }}/{{ folders.programs }}/symfony"
        dest: "/usr/local/bin/symfony"
        state: link
        force: true
