---
- hosts: localhost
  pre_tasks:
    - name: Include vars
      include_vars: ../vars.yml
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ username }}"
          oh_my_zsh:
            theme: "{{ zsh.theme }}"
            plugins: "{{ zsh.plugins }}"
