---
- hosts: localhost
  become: true
  tasks:
    - include_vars: vars.yml

    - name: Update apt
      apt:
        update_cache: true
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install packages
      apt:
        pkg: "{{ apt.packages }}"
