---
- hosts: localhost
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install packages
      apt:
        pkg: "{{ apt.packages }}"

- hosts: localhost
  become: no
  roles:
    - role: gantsign.visual-studio-code