---
- hosts: localhost
  tasks:
    - include_vars: vars.yml

    - name: Check ssh key is installed
      stat:
        path: /home/{{ username }}/.ssh/id_rsa.pub
      register: ssh_installed

    - name: Copy ssh key
      copy:
        src: "{{ item }}"
        dest: /home/{{ username }}/.ssh/
        mode: 0600
      with_fileglob:
        - sshkey/*
      when:
        - not ssh_installed.stat.exists

    - name: Delete ssh key
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - sshkey/*

    - name: Install KDE Neon ssh agent
      import_tasks: sshagent/kdeneon.yml
      when: hostvars[inventory_hostname].ansible_distribution == 'KDE neon'

    - name: Install Ubuntu ssh agent
      import_tasks: sshagent/ubuntu.yml
      when: hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'
