name: Test dotfiles

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install ansible
        run: |
          sudo apt install -y ansible

      - name: Set vars
        run: |
          cp vars.yml.example vars.yml

      - name: Get env details
        run: |
          echo $HOME
          whoami

      - name: Copy ssh key (fake one!)
        run: |
          echo "fake-priv-key" > sshkey/id_rsa
          echo "fake-pub-key" > sshkey/id_rsa.pub

      - name: Install requirements
        run: |
          ansible-galaxy role install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml

      - name: Run ansible
        run: |
          ansible-playbook -vvvv -K main.yml
