name: Test dotfiles

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install ansible
        run: |
          sudo apt install -y ansible

      - name: Set vars
        run: |
          cp vars.yml.ci vars.yml

      - name: Get env details
        run: |
          echo $HOME
          whoami

      - name: Copy ssh key (fake one!)
        run: |
          echo "fake-priv-key" > sshkey/test__id_rsa
          echo "fake-pub-key" > sshkey/test__id_rsa.pub

      - name: Install requirements
        run: |
          ansible-galaxy role install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml

      - name: Run ansible
        run: |
          ansible-playbook -v -K main.yml

      - name: Test ssh key installed
        run: |
          cat $HOME/.ssh/test__id_rsa.pub
